# general configuration
url: http//federicocastaneda.info
#baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/logo.png"
  # author will appear under the avatar (optional)
  author: "Federico Castaneda"
  # tagline will appear under the title (optional)
  tagline: "Front-end dev. Bringing mockups to life on the internet since 2009."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false
  timezone:  America/New_York

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Google Analytics
analytics:
  # Add tracking code in _includes/_google-analytics.html
  google: false
